# Generated by Django 5.0.1 on 2024-01-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('salary', models.IntegerField(default=1)),
                ('location', models.CharField(max_length=10000, null=True)),
                ('type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Intetship', 'Intetship')], default='Full Time', max_length=20)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
